[package]
name = "dioxus-bevy-macro-core"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.85"

[dev-dependencies]
bevy = "0.14.2"
